# Generated by Django 6.0.1 on 2026-01-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0002_rename_menu_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.FloatField(),
        ),
    ]
